USE [master]
GO

/****** Object:  Database [biblioteca]    Script Date: 07/19/2024 12:16:28 ******/
CREATE DATABASE [biblioteca] ON  PRIMARY 
( NAME = N'biblioteca', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\biblioteca.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'biblioteca_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\biblioteca_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [biblioteca] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [biblioteca].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [biblioteca] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [biblioteca] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [biblioteca] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [biblioteca] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [biblioteca] SET ARITHABORT OFF 
GO

ALTER DATABASE [biblioteca] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [biblioteca] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [biblioteca] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [biblioteca] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [biblioteca] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [biblioteca] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [biblioteca] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [biblioteca] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [biblioteca] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [biblioteca] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [biblioteca] SET  DISABLE_BROKER 
GO

ALTER DATABASE [biblioteca] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [biblioteca] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [biblioteca] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [biblioteca] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [biblioteca] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [biblioteca] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [biblioteca] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [biblioteca] SET  READ_WRITE 
GO

ALTER DATABASE [biblioteca] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [biblioteca] SET  MULTI_USER 
GO

ALTER DATABASE [biblioteca] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [biblioteca] SET DB_CHAINING OFF 
GO

